---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: apache
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: apache 
      sourceRef:
        kind: HelmRepository
        name: charts.bitnami.com
        namespace: ${workspaceNamespace}
      version: 11.3.4
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: apache
  valuesFrom:
    - kind: ConfigMap
      name: {{ printf "%s-httpd-conf" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }} 
  targetNamespace: ${releaseNamespace}
