---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github.com.bitnami-helm-releases
  namespace: ${workspaceNamespace}
  labels:
    kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: "${helmMirrorURL:=https://github.com/bitnami/charts}"
  interval: 10m
